# Generated by Django 6.0.1 on 2026-02-12 19:52

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AUTHOR', 'Auteur'), ('CONTRIBUTOR', 'Contributeur')], max_length=20, verbose_name='Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nom du projet')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('type', models.CharField(choices=[('BACK-END', 'Back-end'), ('FRONT-END', 'Front-end'), ('IOS', 'Ios'), ('ANDROID', 'Android')], max_length=10, verbose_name='Type')),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date de creation')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('contributors', models.ManyToManyField(related_name='contributors', through='contribution.Contributor', to=settings.AUTH_USER_MODEL, verbose_name='Contributeurs')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du problème')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute')], default='HIGH', max_length=20, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('TO DO', 'A faire'), ('IN PROGRESS', 'En cours'), ('FINISHED', 'Terminé')], default='TO DO', max_length=20, verbose_name='Statut de progression')),
                ('balise', models.CharField(choices=[('BUG', 'Bug'), ('TASK', 'Tâche'), ('IMPROVEMENT', 'Amélioration')], default='BUG', max_length=20, verbose_name='Balise')),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date de creation')),
                ('attribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Attribué à')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_authors', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribution.project', verbose_name='Projet')),
            ],
        ),
        migrations.AddField(
            model_name='contributor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribution.project', verbose_name='Projet'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('link', models.URLField(verbose_name='Link')),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date de creation')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribution.issue', verbose_name='Issue')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('author', 'issue'), name='unique_comment')],
            },
        ),
        migrations.AddConstraint(
            model_name='contributor',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='unique_contributor'),
        ),
    ]
