# Generated by Django 6.0.1 on 2026-02-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_comment',
        ),
    ]
