# Generated by Django 6.0.1 on 2026-02-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0002_remove_comment_unique_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='balise',
            new_name='tag',
        ),
    ]
