# Generated by Django 6.0.1 on 2026-02-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0003_rename_balise_issue_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(default='Description', max_length=500, verbose_name='Description'),
        ),
    ]
